Name: catalog
ServiceType: ClusterIP
ServicePort: 80
ContainerPort: 9292
Component: "catalog"
Replicas: 3
Image: "enxebre/catalog"
ImageTag: "v2"
IngressDomain: "test"
ImagePullPolicy: "Always"
Cpu: "9m"
Memory: "64Mi"
Version: 0

prometheus-operated-chart:
  componentMonitored: catalog

  prometheus:
    rules:
      test.rules: |
        ALERT httpRequestsSuspicious
        IF http_requests_suspicious > 2

        ALERT remoteCallSlow
        IF remote_calls_summary>1

  alertmanager:
    alertmanagerFiles:
      alertmanager.yaml: |
        global:
          resolve_timeout: 5m
        route:
          group_by: ['job']
          group_wait: 30s
          group_interval: 1m
          repeat_interval: 1m
          receiver: 'default-receiver'
        receivers:
        - name: default-receiver
          slack_configs:
          - api_url: 'https://hooks.slack.com/services/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'
            channel: '#alertv2'
            send_resolved: true
